---

nginx_env:
  RUNLEVEL: 1

nginx_installation_types_using_service: ["packages", "configuration-only"]

nginx_is_el: "{{ ansible_distribution in ['RedHat', 'CentOS'] }}"

nginx_http_default_params:
  - sendfile "on"
  - tcp_nopush "on"
  - tcp_nodelay "on"
  - keepalive_timeout "65"
  - access_log "{{nginx_log_dir}}/access.log"
  - "error_log {{nginx_log_dir}}/error.log {{nginx_error_log_level}}"
  - server_tokens off
  - types_hash_max_size 2048  
  - open_file_cache max=102400 inactive=20s
  - open_file_cache_valid 30s
  - open_file_cache_min_uses 2
  - open_file_cache_errors "on"
  - fastcgi_buffers 256 16k
  - fastcgi_buffer_size 128k
  - fastcgi_connect_timeout "3s"
  - fastcgi_send_timeout "120s"
  - fastcgi_read_timeout "120s"
  - server_names_hash_bucket_size 100

