- hosts: keepalived
  roles:
    - role: lvs-keepalived
      global_defs:
        notification_email:
          - email1@example.com
          - email2@example.com
        notification_email_from: 'keepalived@example.com'
      vrrp_scripts:
        - name: 'chk_haproxy'
          script: 'killall -0 haproxy'
          interval: 2
          weight: 2
      vrrp_instances:
        - name: 'VI_100'
          virtual_router_id: 100
          interface: 'eth0'
          state: 'MASTER'
          priority: 100
          virtual_ipaddress:
            - '192.168.234.100/24 dev eth0'
          auth_pass: 's3cr3tp'
          track_script:
            - chk_haproxy

