---
- name: Run Lmbench
  hosts: WebServerD05
  remote_user: root
  vars_files:
  - roles/stream/vars/main.yml
  tasks:
  - name: run test
    shell: sh ~/{{root_dir}}/{{app_dir}}/{{basic_dir}}/{{tool_dir}}/run_test.sh
  - name: fetch result
    fetch: src=~/result_memory/stream/result_{{item}} dest=~/{{root_dir}}/{{app_dir}}/{{basic_dir}}/{{tool_dir}}/result/ flat=yes
    with_items:
    - 192.168.1.115
    - 192.168.1.225
    - 192.168.1.234
